# docker-compose.yml (Kraft Mode - Using apache/kafka)
version: '3.8'

services:
  kafka:
    image: apache/kafka:3.7.0 # Using a recent stable version that supports Kraft
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      # Kafka broker configuration
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: "PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092"
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LOG_DIRS: "/tmp/kraft-kafka-logs"

      # Kraft mode specific configurations
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:29093"
      KAFKA_CLUSTER_ID: "abcdefghijklmnopqrstuv" # IMPORTANT: Keep this consistent!
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER" # NEW: Explicitly define the controller listener name

      # General Kafka configurations (good defaults)
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    # No custom command needed with apache/kafka image for auto-formatting
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 10s
      timeout: 5s
      retries: 5